// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pyvofnravfmuqobqcpoz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5dm9mbnJhdmZtdXFvYnFjcG96Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NjIzOTAsImV4cCI6MjA3MzQzODM5MH0.oExlw17Q7XCKx4c7FdRFowTGfdcBzZdL0VbPbt518WA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});